/*
 *
 * WwWnPage constants
 *
 */

const DEFAULT_ACTION = 'app/WwWnPage/DEFAULT_ACTION';
const SET_WWWN_KEY_ACTION = 'app/WwWnPage/SET_WWWN_KEY_ACTION';
const GET_WWWN_DATA_ACTION = 'app/WwWnPage/GET_WWWN_DATA_ACTION';
const SET_WWWN_TITLE_ACTION = 'app/WwWnPage/SET_WWWN_TITLE_ACTION';
const SET_WW_DATA_ACTION = 'app/WwWnPage/SET_WW_DATA_ACTION';
const SET_WN_DATA_ACTION = 'app/WwWnPage/SET_WN_DATA_ACTION';
const ADD_WW_DATA_ACTION = 'app/WwWnPage/ADD_WW_DATA_ACTION';
const ADD_WN_DATA_ACTION = 'app/WwWnPage/ADD_WN_DATA_ACTION';

export {
	DEFAULT_ACTION,
	SET_WWWN_KEY_ACTION,
	GET_WWWN_DATA_ACTION,
	SET_WWWN_TITLE_ACTION,
	SET_WW_DATA_ACTION,
	SET_WN_DATA_ACTION,
	ADD_WW_DATA_ACTION,
	ADD_WN_DATA_ACTION,
}