/*
 *
 * PlanPage constants
 *
 */

const DEFAULT_ACTION = 'app/PlanPage/DEFAULT_ACTION';
const GET_PLAN_ACTION = 'app/PlanPage/GET_PLAN_ACTION';

export {
	DEFAULT_ACTION,
	GET_PLAN_ACTION,
	SET_PLAN_KEY_ACTION,
	SET_EVENT_OPTIONS_ACTION,
	SET_SCHEDULE_ACTION,
}