/*
 *
 * PlanPage constants
 *
 */

const DEFAULT_ACTION = 'app/PlanPage/DEFAULT_ACTION';
const GET_PLAN_ACTION = 'app/PlanPage/GET_PLAN_ACTION';
const SET_PLAN_KEY_ACTION = 'app/PlanPage/SET_PLAN_KEY_ACTION';
const SET_EVENT_OPTIONS_ACTION = 'app/PlanPage/SET_EVENT_OPTIONS_ACTION';
const SET_SCHEDULE_ACTION = 'app/PlanPage/SET_SCHEDULE_ACTION';
const DELETE_SCHEDULE_ITEM_ACTION = 'app/PlanPage/DELETE_SCHEDULE_ITEM_ACTION';

export {
	DEFAULT_ACTION,
	GET_PLAN_ACTION,
	SET_PLAN_KEY_ACTION,
	SET_EVENT_OPTIONS_ACTION,
	SET_SCHEDULE_ACTION,
	DELETE_SCHEDULE_ITEM_ACTION,
}