/*
 *
 * RunPage constants
 *
 */

const DEFAULT_ACTION = 'app/RunPage/DEFAULT_ACTION';
const GET_PLAN_ACTION = 'app/RunPage/GET_PLAN_ACTION';
const SET_PLAN_KEY_ACTION = 'app/RunPage/SET_PLAN_KEY_ACTION';
const SET_SCHEDULE_ACTION = 'app/RunPage/SET_SCHEDULE_ACTION';

export {
	DEFAULT_ACTION,
	GET_PLAN_ACTION,
	SET_PLAN_KEY_ACTION,
	SET_SCHEDULE_ACTION,
}